export { provideWorld, useWorld } from './useWorld'
export { useQuery } from './useQuery.svelte'
export { useTrait } from './useTrait.svelte'
export { useTag } from './useTag.svelte'
export { useTarget } from './useTarget.svelte'
export { useParentName } from './useParentName.svelte'
export { provideHierarchy } from './provideHierarchy.svelte'
export { provideWorldMatrix } from './provideWorldMatrix.svelte'
export { setOrAddTrait } from './setOrAddTrait'

export * as traits from './traits'
export * as relations from './relations'
export * as hierarchy from './hierarchy'
