// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: draw/v1/worldstate.proto

package drawv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DrawingProjection is merged into a viam.common.v1.Transform's metadata when a Drawing
// travels over the world_state_store API.
//
// That API carries only common.v1.Geometry, so a Shape has no native home and rides in the
// metadata Struct instead, next to draw.v1.Metadata's fields.
//
// Both halves are encoded with protojson using proto field names and numeric enums.
type DrawingProjection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The shape this transform really is. Present only on projected Drawings; a Transform
	// that carries no shape is a true Transform and renders from its physical_object.
	Shape         *Shape `protobuf:"bytes,1,opt,name=shape,proto3" json:"shape,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrawingProjection) Reset() {
	*x = DrawingProjection{}
	mi := &file_draw_v1_worldstate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrawingProjection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrawingProjection) ProtoMessage() {}

func (x *DrawingProjection) ProtoReflect() protoreflect.Message {
	mi := &file_draw_v1_worldstate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrawingProjection.ProtoReflect.Descriptor instead.
func (*DrawingProjection) Descriptor() ([]byte, []int) {
	return file_draw_v1_worldstate_proto_rawDescGZIP(), []int{0}
}

func (x *DrawingProjection) GetShape() *Shape {
	if x != nil {
		return x.Shape
	}
	return nil
}

var File_draw_v1_worldstate_proto protoreflect.FileDescriptor

const file_draw_v1_worldstate_proto_rawDesc = "" +
	"\n" +
	"\x18draw/v1/worldstate.proto\x12\adraw.v1\x1a\x15draw/v1/drawing.proto\"9\n" +
	"\x11DrawingProjection\x12$\n" +
	"\x05shape\x18\x01 \x01(\v2\x0e.draw.v1.ShapeR\x05shapeB2Z0github.com/viam-labs/motion-tools/draw/v1;drawv1b\x06proto3"

var (
	file_draw_v1_worldstate_proto_rawDescOnce sync.Once
	file_draw_v1_worldstate_proto_rawDescData []byte
)

func file_draw_v1_worldstate_proto_rawDescGZIP() []byte {
	file_draw_v1_worldstate_proto_rawDescOnce.Do(func() {
		file_draw_v1_worldstate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_draw_v1_worldstate_proto_rawDesc), len(file_draw_v1_worldstate_proto_rawDesc)))
	})
	return file_draw_v1_worldstate_proto_rawDescData
}

var file_draw_v1_worldstate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_draw_v1_worldstate_proto_goTypes = []any{
	(*DrawingProjection)(nil), // 0: draw.v1.DrawingProjection
	(*Shape)(nil),             // 1: draw.v1.Shape
}
var file_draw_v1_worldstate_proto_depIdxs = []int32{
	1, // 0: draw.v1.DrawingProjection.shape:type_name -> draw.v1.Shape
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_draw_v1_worldstate_proto_init() }
func file_draw_v1_worldstate_proto_init() {
	if File_draw_v1_worldstate_proto != nil {
		return
	}
	file_draw_v1_drawing_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_draw_v1_worldstate_proto_rawDesc), len(file_draw_v1_worldstate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_draw_v1_worldstate_proto_goTypes,
		DependencyIndexes: file_draw_v1_worldstate_proto_depIdxs,
		MessageInfos:      file_draw_v1_worldstate_proto_msgTypes,
	}.Build()
	File_draw_v1_worldstate_proto = out.File
	file_draw_v1_worldstate_proto_goTypes = nil
	file_draw_v1_worldstate_proto_depIdxs = nil
}
